vagrant:
  acme: false
  agora_revision: master
  autopilot_active: true
  bitcoind_requires: ""
  content_revision: master
  domain: 192.168.50.4
  ipv4: 192.168.50.4
  ipv6: fde4:8dba:82e1::c4
  lnd:
    rpclisten: 0.0.0.0
    tlsextradomain: ~
  network: regtest

kos:
  acme: true
  agora_revision: master
  autopilot_active: true
  bitcoind_requires: ""
  content_revision: master
  domain: test.agora.download
  ipv4: 66.175.211.57
  ipv6: 2600:3c03::f03c:92ff:fe31:d717
  lnd:
    rpclisten: 0.0.0.0
    tlsextradomain: test.agora.download
  network: testnet

athens:
  acme: true
  agora_revision: master
  autopilot_active: false
  bitcoind_requires: Requires=mnt-athens.mount
  blocksdir: /mnt/athens/
  content_revision: master
  domain: agora.download
  ipv4: 66.175.216.63
  ipv6: 2600:3c01::f03c:92ff:fe75:056f
  lnd:
    rpclisten: 127.0.0.1
    tlsextradomain: agora.download
  network: mainnet
