[logger]
type = "production"
dest = "/root/.lntop/lntop.log"

[network]
name = "lnd"
type = "lnd"
address = "//127.0.0.1:10009"
cert = "/var/lib/lnd/tls.cert"
macaroon = "/var/lib/lnd/data/chain/bitcoin/{{ network }}/admin.macaroon"
macaroon_timeout = 60
max_msg_recv_size = 52428800
conn_timeout = 1000000
pool_capacity = 4

[views]
# views.channels is the view displaying channel list.
[views.channels]
# It is possible to add, remove and order columns of the
# table with the array columns. The available values are:
columns = [
  "STATUS",      # status of the channel
  "ALIAS",       # alias of the channel node
  "GAUGE",       # ascii bar with percent local/capacity
  "LOCAL",       # the local amount of the channel
  "CAP",         # the total capacity of the channel
  "SENT",        # the total amount sent
  "RECEIVED",    # the total amount received
  "HTLC",        # the number of pending HTLC
  "UNSETTLED",   # the amount unsettled in the channel
  "CFEE",        # the commit fee
  "LAST UPDATE", # last update of the channel
  "PRIVATE",     # true if channel is private
  "ID",          # the id of the channel
]

[views.transactions]
# It is possible to add, remove and order columns of the
# table with the array columns. The available values are:
columns = [
  "DATE",      # date of the transaction
  "HEIGHT",    # block height of the transaction
  "CONFIR",    # number of confirmations
  "AMOUNT",    # amount moved by the transaction
  "FEE",       # fee of the transaction
  "ADDRESSES", # number of transaction output addresses
]

[views.routing]
columns = [
  "DIR",            # event type:  send, receive, forward
  "STATUS",         # one of: active, settled, failed, linkfail
  "IN_CHANNEL",     # channel id of the incomming channel
  "IN_ALIAS",       # incoming channel node alias
  # "IN_HTLC",      # htlc id on incoming channel
  # "IN_TIMELOCK",  # incoming timelock height
  "OUT_CHANNEL",    # channel id of the outgoing channel
  "OUT_ALIAS",      # outgoing channel node alias
  # "OUT_HTLC",     # htlc id on outgoing channel
  # "OUT_TIMELOCK", # outgoing timelock height
  "AMOUNT",         # routed amount
  "FEE",            # routing fee
  "LAST UPDATE",    # last update
  "DETAIL",         # error description
]
